"""Init

Revision ID: fff4404ff823
Revises: 
Create Date: 2022-06-07 14:27:03.964408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fff4404ff823"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasktypes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("project", sa.Integer(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type"],
            ["tasktypes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "works",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task", sa.Integer(), nullable=True),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("works")
    op.drop_table("tasks")
    op.drop_table("tasktypes")
    op.drop_table("projects")
    # ### end Alembic commands ###
